
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import libraryScene from '../assets/3d/library.glb'
// To create animated groups
import { a } from '@react-spring/three'

const Library = (props) => {
    // Create a ref
    const libraryRef = useRef();

  const { nodes, materials } = useGLTF(libraryScene)
  return (
    <a.group {...props} ref={libraryRef}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_FloorBoard_M_Wood_5_0.geometry}
            material={materials.M_Wood_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Book_Cat_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Book_Cat_M_Cover_Color_5_0.geometry}
            material={materials.M_Cover_Color_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Cover_Color_5_0.geometry}
            material={materials.M_Cover_Color_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Pencil_0.geometry}
            material={materials.M_Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Carpet_M_Cat_Nose_Ears_0.geometry}
            material={materials.M_Cat_Nose_Ears}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Cover_Color_4_0.geometry}
            material={materials.M_Cover_Color_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Cover_Color_2_0.geometry}
            material={materials.M_Cover_Color_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Cover_Color_1_0.geometry}
            material={materials.M_Cover_Color_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Cover_Color_3_0.geometry}
            material={materials.M_Cover_Color_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Ladder_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Cover_Color_1_0.geometry}
            material={materials.M_Cover_Color_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Scroll_Tie_0.geometry}
            material={materials.M_Scroll_Tie}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Cover_Color_2_0.geometry}
            material={materials.M_Cover_Color_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Cover_Color_5_0.geometry}
            material={materials.M_Cover_Color_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Cover_Color_4_0.geometry}
            material={materials.M_Cover_Color_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Cover_Color_3_0.geometry}
            material={materials.M_Cover_Color_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Shelves_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_M_Cover_Color_3_0.geometry}
            material={materials.M_Cover_Color_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Cover_Color_3_0.geometry}
            material={materials.M_Cover_Color_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Cover_Color_5_0.geometry}
            material={materials.M_Cover_Color_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Cover_Color_1_0.geometry}
            material={materials.M_Cover_Color_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Cover_Color_2_0.geometry}
            material={materials.M_Cover_Color_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Scroll_Tie_0.geometry}
            material={materials.M_Scroll_Tie}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Unfinished_0.geometry}
            material={materials.M_Unfinished}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Painting_3_0.geometry}
            material={materials.M_Painting_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Cover_Color_4_0.geometry}
            material={materials.M_Cover_Color_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Books_Table_Beneath_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Shelf_M_Bottles_3_0.geometry}
            material={materials.M_Bottles_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Shelf_M_Wood3_0.geometry}
            material={materials.M_Wood3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Shelf_M_Bottle_2_0.geometry}
            material={materials.M_Bottle_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Shelf_M_Bottle_1_0.geometry}
            material={materials.M_Bottle_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Bottle_1_0.geometry}
            material={materials.M_Bottle_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Wood_4_0.geometry}
            material={materials.M_Wood_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Bottle_2_0.geometry}
            material={materials.M_Bottle_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Wood3_0.geometry}
            material={materials.M_Wood3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Bottles_Table_M_Cover_Color_1_0.geometry}
            material={materials.M_Cover_Color_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Carpet_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Carpet_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Cat_M_Cat_Eyes_0.geometry}
            material={materials.M_Cat_Eyes}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Cat_M_Cat_0.geometry}
            material={materials.M_Cat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Cat_M_Cat_Nose_Ears_0.geometry}
            material={materials.M_Cat_Nose_Ears}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Chair_M_Wood_1_0.geometry}
            material={materials.M_Wood_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Chair_M_Wood_2_0.geometry}
            material={materials.M_Wood_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Drawer_M_Lamp_Yellow_2_0.geometry}
            material={materials.M_Lamp_Yellow_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Drawer_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Drawer_M_Wood_5_0.geometry}
            material={materials.M_Wood_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Drawer_M_Wood_1_0.geometry}
            material={materials.M_Wood_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Drawer_M_Wood_4_0.geometry}
            material={materials.M_Wood_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Glasses_M_Glasses_0.geometry}
            material={materials.M_Glasses}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Ladder_M_Wood_2_0.geometry}
            material={materials.M_Wood_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Ladder_M_Wood_1_0.geometry}
            material={materials.M_Wood_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Lamp_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Lamp_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Lamp_M_Lamp_Yellow_2_0.geometry}
            material={materials.M_Lamp_Yellow_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Lamp_M_Lamp_Yellow_1_0.geometry}
            material={materials.M_Lamp_Yellow_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Left_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Left_M_Painting_3_0.geometry}
            material={materials.M_Painting_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Left_M_Painting_2_0.geometry}
            material={materials.M_Painting_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Left_M_Painting_1_0.geometry}
            material={materials.M_Painting_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Left_M_Painting_4_0.geometry}
            material={materials.M_Painting_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Right_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Right_M_Painting_2_0.geometry}
            material={materials.M_Painting_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Right_M_Painting_4_0.geometry}
            material={materials.M_Painting_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Right_M_Painting_1_0.geometry}
            material={materials.M_Painting_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Paintings_Right_M_Painting_3_0.geometry}
            material={materials.M_Painting_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Papers_Table_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Pencils_Table_M_Pencil_0.geometry}
            material={materials.M_Pencil}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Pencils_Table_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Pencils_Table_M_Carpet_Color2_0.geometry}
            material={materials.M_Carpet_Color2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Pencils_Table_M_Cover_Color_4_0.geometry}
            material={materials.M_Cover_Color_4}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Picture_Frames_M_Carpet_Color1_0.geometry}
            material={materials.M_Carpet_Color1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Picture_Frames_M_Painting_2_0.geometry}
            material={materials.M_Painting_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Picture_Frames_M_Painting_3_0.geometry}
            material={materials.M_Painting_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Plants_Shelf_M_Cover_Color_3_0.geometry}
            material={materials.M_Cover_Color_3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Plants_Shelf_M_Cover_Color_2_0.geometry}
            material={materials.M_Cover_Color_2}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Plants_Shelf_M_Wood_1_0.geometry}
            material={materials.M_Wood_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Plants_Shelf_M_Cover_Color_1_0.geometry}
            material={materials.M_Cover_Color_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Plants_Shelf_M_Cover_Color_5_0.geometry}
            material={materials.M_Cover_Color_5}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Quill_M_Rat_0.geometry}
            material={materials.M_Rat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Quill_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Quill_M_Feather_0.geometry}
            material={materials.M_Feather}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Rat_M_Rat_0.geometry}
            material={materials.M_Rat}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Rat_M_Cat_Nose_Ears_0.geometry}
            material={materials.M_Cat_Nose_Ears}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Scrolls_Drawer_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Scrolls_Drawer_M_Scroll_Tie_0.geometry}
            material={materials.M_Scroll_Tie}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Scrolls_Shelf_M_Gold_0.geometry}
            material={materials.M_Gold}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Scrolls_Shelf_M_Paper_0.geometry}
            material={materials.M_Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Scrolls_Shelf_M_Scroll_Tie_0.geometry}
            material={materials.M_Scroll_Tie}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Shelf_M_Wood3_0.geometry}
            material={materials.M_Wood3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Shelf_M_Wood_2_0.geometry}
            material={materials.M_Wood_2}
          />
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Stars_M_Cat_0.geometry}
            material={materials.M_Cat}
          /> */}
          {/* <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Stars_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          /> */}
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Table_M_Wood_1_0.geometry}
            material={materials.M_Wood_1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Table_M_Wood3_0.geometry}
            material={materials.M_Wood3}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Tea_M_Porcelain_Blue_0.geometry}
            material={materials.M_Porcelain_Blue}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Tea_M_Porcelain_0.geometry}
            material={materials.M_Porcelain}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Tea_M_Tea_0.geometry}
            material={materials.M_Tea}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Tea_M_Steam_0.geometry}
            material={materials.M_Steam}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Book_Cover_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Book_Paper_M_Paper_Written_0.geometry}
            material={materials.M_Paper_Written}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Book_Paper_M_Paper_Wall_0.geometry}
            material={materials.M_Paper_Wall}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Lamp_M_Book_Cover_0.geometry}
            material={materials.M_Book_Cover}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Lamp_M_Lamp_Rim_0.geometry}
            material={materials.M_Lamp_Rim}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.SM_Wall_Lamp_M_Stars_0.geometry}
            material={materials.M_Stars}
          />
        </group>
      </group>
    </a.group>
  )
}

export default Library;